# ranger setup playbook
#
#   ansible-ranger.yml
---
- name: ranger setup
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    - name: install ranger
      yum:
        name: ranger
        state: present
    - name: setup ranger shortcut alias
      blockinfile:
        path: "/home/{{ user }}/.bashrc"
        marker: "# {mark} ranger ANSIBLE MANAGED BLOCK"
        block: |
          # ranger shortcut
          alias r="ranger"
    - name: create ~/.config/ranger
      file:
        path: "/home/{{ user }}/.config/ranger"
        state: directory
      become_user: "{{ user }}"
    - name: get new ranger config stats
      stat:
        path: "/home/{{ user }}/data/config/rc.conf"
      register: new_ranger_conf
    - name: setup ranger config
      file:
        src: "/home/{{ user }}/data/config/rc.conf"
        dest: "/home/{{ user }}/.config/ranger/rc.conf"
        state: link
        force: true
      become_user: "{{ user }}"
      when: new_ranger_conf.stat.exists == true
