# directories setup playbook
#
#   ansible-dir.yml
---
- name: dir setup
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    - name: create user directories
      file:
        path: "/home/{{ user }}/{{ item }}"
        state: directory
      become_user: "{{ user }}"
      loop:
        - "data"
        - "games"
        - "log"
        - "osoukup"
        - "test"

    - name: remove unused default directories
      file:
        path: "/home/{{ user }}/{{ item }}"
        state: absent
      loop:
        - "Documents"
        - "Music"
        - "Pictures"
        - "Public"
        - "Templates"
        - "Videos"
