# ranger setup playbook
#
#   ansible-ranger.yml
---
- name: ranger setup
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    - name: install ranger
      yum:
        name: ranger
        state: present

    - name: setup ranger shortcut alias
      blockinfile:
        path: "/home/{{ user }}/.bashrc"
        marker: "# {mark} ranger ANSIBLE MANAGED BLOCK"
        block: |
          # ranger shortcut
          alias r="ranger"

    - name: create default ranger configs
      command: "ranger --copy-config=all"
      changed_when: false
      become_user: "{{ user }}"

    - name: setup ranger stuff in rc.conf
      blockinfile:
        path: "/home/{{ user }}/.config/ranger/rc.conf"
        marker: "# {mark} ranger ANSIBLE MANAGED BLOCK"
        block: |
          # remapped keys
          map l    move up=1
          map k    move down=1
          map j    move left=1
          map ů    move right=1
