# random stuff setup playbook
# - things which do not fit elsewhere
#
#   ansible-random.yml
---
- name: random setup
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    - name: setup modified cz keyboard layout
      copy:
        src: "/home/{{ user }}/data/config/cz"
        dest: "/usr/share/X11/xkb/symbols/cz"
        mode: "0644"
    - name: display system restart requirement info
      debug:
        msg: "System restart required for keyboard layout change to take effect!"

    - name: symlink .bashrc file
      file:
        src: "/home/{{ user }}/data/config/dot-bashrc"
        dest: "/home/{{ user }}/.bashrc"
        state: link
        force: true
      become_user: "{{ user }}"

    - name: create ~/.config
      file:
        path: "/home/{{ user }}/.config"
        state: directory
      become_user: "{{ user }}"

    - name: install flake8
      dnf:
        name: python3-flake8
        state: present
    - name: get new flake8 config stats
      stat:
        path: "/home/{{ user }}/data/config/flake8"
      register: new_flake8
    - name: setup flake8 config
      file:
        src: "/home/{{ user }}/data/config/flake8"
        dest: "/home/{{ user }}/.config/flake8"
        state: link
        force: true
      become_user: "{{ user }}"
      when: new_flake8.stat.exists == true

    # setup start script
    - name: create ~/.config/autostart
      file:
        path: "/home/{{ user }}/.config/autostart"
        state: directory
      become_user: "{{ user }}"
    - name: get new start script stats
      stat:
        path: "/home/{{ user }}/data/startup/start.desktop"
      register: new_start
    - name: setup start script
      file:
        src: "/home/{{ user }}/data/startup/start.desktop"
        dest: "/home/{{ user }}/.config/autostart/start.desktop"
        state: link
        force: true
      become_user: "{{ user }}"
      when: new_start.stat.exists == true

    # install bat
    # otherwise cat does not work due to alias
    - name: install bat
      dnf:
        name: bat
        state: present

    # installing vlc
    # requires rmpfusion
    - name: get Fedora version
      shell: cut -d\  -f3 /etc/fedora-release
      register: fedora_version
      changed_when: false
    - name: install rpmfusion-free
      dnf:
        name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm"
        state: present
        disable_gpg_check: true
    - name: install rpmfusion-nonfree
      dnf:
        name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version.stdout }}.noarch.rpm"
        state: present
        disable_gpg_check: true
    - name: install vlc
      dnf:
        name: vlc
        state: present

    # GNOME setup
    - name: install GNOME stuff
      dnf:
        name:
          - gnome-tweak-tool
          - dconf-editor
          - python3-psutil  # needed for dconf in the next step
        state: present
    - name: setup GNOME config
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.val }}"
        state: present
      become_user: "{{ user }}"
      loop:
        # remap keys
        - key: "/org/gnome/desktop/wm/keybindings/close"
          val: "['<Alt>q', '<Alt>F4']"
        - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-down"
          val: "['<Super><Shift>Page_Down', '<Control><Shift><Alt>Down', '<Control><Shift><Alt>k']"
        - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left"
          val: "['<Control><Shift><Alt>Left', '<Control><Shift><Alt>j']"
        - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-right"
          val: "['<Control><Shift><Alt>Right', '<Control><Shift><Alt>uring']"
        - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-up"
          val: "['<Super><Shift>Page_Up', '<Control><Shift><Alt>Up', '<Control><Shift><Alt>l']"
        - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-down"
          val: "['<Super>Page_Down', '<Control><Alt>Down', '<Control><Alt>k']"
        - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left"
          val: "['<Control><Alt>Left', '<Control><Alt>j']"
        - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right"
          val: "['<Control><Alt>Right', '<Control><Alt>uring']"
        - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-up"
          val: "['<Super>Page_Up', '<Control><Alt>Up', '<Control><Alt>l']"
        # set max 4 workspaces
        - key: "/org/gnome/desktop/wm/preferences/num-workspaces"
          val: "4"
        - key: "/org/gnome/mutter/dynamic-workspaces"
          val: "false"
        # and alt+tab workspace isolated
        - key: "/org/gnome/shell/app-switcher/current-workspace-only"
          val: "true"
        # turn off alert sound
        - key: "/org/gnome/desktop/sound/event-sounds"
          val: "false"
        # allow 100%+ volume
        - key: "/org/gnome/desktop/sound/allow-volume-above-100-percent"
          val: "true"
        # alt-tab on the current workspace only
        - key: "/org/gnome/shell/app-switcher/current-workspace-only"
          val: "true"
        # no colored terminal status reporting
        - key: "/org/gnome/Ptyxis/visual-process-leader"
          val: "false"

    # install and setup development tools
    - name: create ~/.did
      file:
        path: "/home/{{ user }}/.did"
        state: directory
      become_user: "{{ user }}"
    - name: install development tools
      dnf:
        name:
          - did
          - gcc
          - httpie
          - jq
          - make
          - meld
          - tldr
          - vagrant
        state: present
    - name: install rhpaste
      ansible.builtin.pip:
        name: rhpaste
        extra_args: --user
      become_user: "{{ user }}"

    - name: check boot menu timeout
      ansible.builtin.lineinfile:
        line: "GRUB_TIMEOUT=0"
        path: "/etc/default/grub"
        state: present
      check_mode: yes
      register: out

    - name: disable boot menu
      block:
        - name: replace boot menu timeout
          ansible.builtin.replace:
            path: "/etc/default/grub"
            regexp: "GRUB_TIMEOUT=[0-9]+"
            replace: "GRUB_TIMEOUT=0"
        - name: update grub2 config
          ansible.builtin.shell: grub2-mkconfig -o /boot/grub2/grub.cfg
      when: out.changed

    - name: install random graphical stuff
      dnf:
        name:
          - feh
          - kolourpaint
        state: present

    - name: install mediawriter
      dnf:
        name: mediawriter
        state: present
