# random stuff setup playbook
# - things which do not fit elsewhere
#
#   ansible-random.yml
---
- name: random setup
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    - name: setup modified cz keyboard layout
      copy:
        src: "/home/{{ user }}/data/config/cz"
        dest: "/usr/share/X11/xkb/symbols/cz"
        mode: "0644"
    - name: display system restart requirement info
      debug:
        msg: "System restart required for keyboard layout change to take effect!"

    - name: symlink .bashrc file
      file:
        src: "/home/{{ user }}/data/config/dot-bashrc"
        dest: "/home/{{ user }}/.bashrc"
        state: link
        force: true
      become_user: "{{ user }}"

    - name: create ~/.config
      file:
        path: "/home/{{ user }}/.config"
        state: directory
      become_user: "{{ user }}"

    - name: install flake8
      dnf:
        name: python3-flake8
        state: present
    - name: get new flake8 config stats
      stat:
        path: "/home/{{ user }}/data/config/flake8"
      register: new_flake8
    - name: setup flake8 config
      file:
        src: "/home/{{ user }}/data/config/flake8"
        dest: "/home/{{ user }}/.config/flake8"
        state: link
        force: true
      become_user: "{{ user }}"
      when: new_flake8.stat.exists == true

    # setup start script
    - name: create ~/.config/autostart
      file:
        path: "/home/{{ user }}/.config/autostart"
        state: directory
      become_user: "{{ user }}"
    - name: get new start script stats
      stat:
        path: "/home/{{ user }}/data/startup/start.desktop"
      register: new_start
    - name: setup start script
      file:
        src: "/home/{{ user }}/data/startup/start.desktop"
        dest: "/home/{{ user }}/.config/autostart/start.desktop"
        state: link
        force: true
      become_user: "{{ user }}"
      when: new_start.stat.exists == true

    # install bat
    # otherwise cat does not work due to alias
    - name: install bat
      dnf:
        name: bat
        state: present

    - name: install browsers
      dnf:
        name:
          - chromium
          - firefox
        state: present

    # installing vlc
    # requires rmpfusion
    - name: get Fedora version
      shell: cut -d\  -f3 /etc/fedora-release
      register: fedora_version
      changed_when: false
    - name: install rpmfusion-free
      dnf:
        name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm"
        state: present
        disable_gpg_check: true
    - name: install rpmfusion-nonfree
      dnf:
        name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version.stdout }}.noarch.rpm"
        state: present
        disable_gpg_check: true
    - name: install vlc
      dnf:
        name: vlc
        state: present

    # GNOME setup
    - name: install GNOME stuff
      dnf:
        name:
          - gnome-tweak-tool
          - dconf-editor
        state: present
    - name: setup GNOME config
      shell: /home/{{ user }}/data/config/gnome-config.sh
      become_user: "{{ user }}"
      # TODO implement some change recognition
      changed_when: false

    # install and setup development tools
    - name: create ~/.did
      file:
        path: "/home/{{ user }}/.did"
        state: directory
      become_user: "{{ user }}"
    - name: install development tools
      dnf:
        name:
          - did
          - gcc
          - httpie
          - jq
          - make
          - meld
          - vagrant
        state: present

    - name: install random graphical stuff
      dnf:
        name:
          - feh
          - kolourpaint
        state: present

    - name: install mediawriter
      dnf:
        name: mediawriter
        state: present
