# system setup playbook
#
# * define user variable as argument
#
#   ansible-setup.yml -e "user=vagrant"
---
- name: system setup
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

- name: ranger setup
  import_playbook: ansible-ranger.yml
  vars:
    user: "{{ user }}"

- name: tmux setup
  import_playbook: ansible-tmux.yml
  vars:
    user: "{{ user }}"

- name: vim setup
  import_playbook: vim/ansible-vim.yml
  vars:
    user: "{{ user }}"
