# system setup playbook
#
# * define user variable as argument
#
#   ansible-setup.yml -e "user=vagrant"
---
- name: dropbox setup
  import_playbook: ansible-dropbox.yml
  vars:
    user: "{{ user }}"

- name: system setup
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    # check .bashrc file is symlink and remove if not
    # otherwise SELinux prevents creating symlink from file
    - name: register .bashrc file
      stat:
        path: "/home/{{ user }}/.bashrc"
      register: bashrc_file
    - name: remove .bashrc file if not symlink
      file:
        state: absent
        path: "/home/{{ user }}/.bashrc"
      when: >
        bashrc_file.stat.exists == true and
        ( bashrc_file.stat.islnk is not defined or bashrc_file.stat.islnk == false )
    - name: symlink .bashrc file
      file:
        src: "/home/{{ user }}/data/config/dot-bashrc"
        dest: "/home/{{ user }}/.bashrc"
        state: link
      become_user: "{{ user }}"

- name: dir setup
  import_playbook: ansible-dir.yml
  vars:
    user: "{{ user }}"

- name: git setup
  import_playbook: ansible-git.yml
  vars:
    user: "{{ user }}"

- name: keys setup
  import_playbook: ansible-keys.yml
  vars:
    user: "{{ user }}"

- name: prodsec setup
  import_playbook: ansible-prodsec.yml
  vars:
    user: "{{ user }}"

- name: random setup
  import_playbook: ansible-random.yml
  vars:
    user: "{{ user }}"

- name: ranger setup
  import_playbook: ansible-ranger.yml
  vars:
    user: "{{ user }}"

- name: tmux setup
  import_playbook: ansible-tmux.yml
  vars:
    user: "{{ user }}"

- name: vim setup
  import_playbook: vim/ansible-vim.yml
  vars:
    user: "{{ user }}"

- name: wiki setup
  import_playbook: wiki/ansible-wiki.yml
  vars:
    user: "{{ user }}"
