# dropbox setup playbook
#
#   ansible-dropbox.yml
---
- name: dropbox setup
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    - name: install dropbox
      yum:
        name: dropbox
        state: present

    # login into the Dropbox manually in browser through Google login
    # start with : dropbox start -i : and follow the instuctions

    - name: register Dropbox data directory
      stat:
        path: "/home/{{ user }}/Dropbox/data"
      register: dropbox_dir
    - name: check Dropbox data directory exists
      assert:
        that:
          - dropbox_dir.stat.exists == true
          - dropbox_dir.stat.isdir is defined and dropbox_dir.stat.isdir
        fail_msg: "setup Dropbox manually : dropbox start -i"

    - name: symlink data directory to Dropbox data directory
      file:
        src: "/home/{{ user }}/Dropbox/data"
        dest: "/home/{{ user }}/data"
        state: link
        force: true
      become_user: "{{ user }}"
