# directories setup playbook
#
# * define user variable as argument
#
#   ansible-dir.yml -e "user=vagrant"
---
- name: dir setup
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    - name: create ~/osoukup
      file:
        path: "/home/{{ user }}/osoukup"
        state: directory
      become_user: "{{ user }}"
    - name: create ~/data
      file:
        path: "/home/{{ user }}/data"
        state: directory
      become_user: "{{ user }}"
    - name: create ~/games
      file:
        path: "/home/{{ user }}/games"
        state: directory
      become_user: "{{ user }}"
    - name: create ~/log
      file:
        path: "/home/{{ user }}/log"
        state: directory
      become_user: "{{ user }}"
    - name: create ~/test
      file:
        path: "/home/{{ user }}/test"
        state: directory
      become_user: "{{ user }}"
