# fun stuff setup playbook
#
#   ansible-fun.yml
---
- name: fun stuff setup
  hosts: all
  tasks:
    - name: install steam
      yum:
        name: steam
        state: present

    - name: install skypeforlinux
      yum:
        name: "https://go.skype.com/skypeforlinux-64.rpm"
        state: present

    # webcam setup and test stuff
    - name: install gtk-v4l
      yum:
        name: gtk-v4l
        state: present
    - name: install cheese
      yum:
        name: cheese
        state: present
