# tmux setup playbook
#
#   ansible-tmux.yml
---
- name: tmux setup
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    - name: install tmux
      dnf:
        name: tmux
        state: present
    - name: setup tmux shortcut aliases
      blockinfile:
        path: "/home/{{ user }}/.bashrc"
        marker: "# {mark} tmux ANSIBLE MANAGED BLOCK"
        block: |
          # tmux shortcuts
          alias ta="tmux attach -t"
          alias tl="tmux ls"
          alias tn="tmux new -s"
    - name: setup tmux plugin manager
      git:
        repo: "https://github.com/tmux-plugins/tpm.git"
        dest: "/home/{{ user }}/.tmux/plugins/tpm"
      become: yes
      become_user: "{{ user }}"
    - name: display manual plugins install requirement info
      debug:
        msg: "Hit CTRL+I in tmux for installing the plugins!"
    - name: get new tmux config stats
      stat:
        path: "/home/{{ user }}/data/config/dot-tmux.conf"
      register: new_tmux_conf
    - name: setup tmux config
      file:
        src: "/home/{{ user }}/data/config/dot-tmux.conf"
        dest: "/home/{{ user }}/.tmux.conf"
        state: link
        force: true
      become_user: "{{ user }}"
      when: new_tmux_conf.stat.exists == true
