# fun stuff setup playbook
#
#   ansible-fun.yml
---
- name: fun stuff setup
  hosts: all
  tasks:
    - name: install steam
      dnf:
        name: steam
        state: present

    # webcam setup and test stuff
    - name: install gtk-v4l
      dnf:
        name: gtk-v4l
        state: present
    - name: install cheese
      dnf:
        name: cheese
        state: present
