# random stuff setup playbook
# - things which do not fit elsewhere
#
# * define user variable as argument
#
#   ansible-random.yml -e "user=vagrant"
---
- name: random setup
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    - name: setup modified cz keyboard layout
      copy:
        src: "/home/{{ user }}/data/config/cz"
        dest: "/usr/share/X11/xkb/symbols/cz"
        mode: "0644"
    - name: display system restart requirement info
      debug:
        msg: "System restart required for keyboard layout change to take effect!"

    # check .bashrc file is symlink and remove if not
    # otherwise SELinux prevents creating symlink from file
    - name: register .bashrc file
      stat:
        path: "/home/{{ user }}/.bashrc"
      register: bashrc_file
    - name: remove .bashrc file if not symlink
      file:
        state: absent
        path: "/home/{{ user }}/.bashrc"
      when: >
        bashrc_file.stat.exists == true and
        ( bashrc_file.stat.islnk is not defined or bashrc_file.stat.islnk == false )
    - name: symlink .bashrc file
      file:
        src: "/home/{{ user }}/data/config/dot-bashrc"
        dest: "/home/{{ user }}/.bashrc"
        state: link
      become_user: "{{ user }}"

    - name: create ~/.config
      file:
        path: "/home/{{ user }}/.config"
        state: directory
      become_user: "{{ user }}"

    - name: get new flake8 config stats
      stat:
        path: "/home/{{ user }}/data/config/flake8"
      register: new_flake8
    - name: setup flake8 config
      block:
        # check flake8 config is symlink and remove if not
        # otherwise SELinux prevents creating symlink from file
        - name: get old flake8 config stats
          stat:
            path: "/home/{{ user }}/.config/flake8"
          register: old_flake8
        - name: remove old flake8 config if not symlink
          file:
            state: absent
            path: "/home/{{ user }}/.config/flake8"
          when: >
            old_flake8.stat.exists == true and
            ( old_flake8.stat.islnk is not defined or old_flake8.stat.islnk == false )
        - name: symlink new flake8 config
          file:
            src: "/home/{{ user }}/data/config/flake8"
            dest: "/home/{{ user }}/.config/flake8"
            state: link
          become_user: "{{ user }}"
      when: new_flake8.stat.exists == true

    # setup start script
    - name: create ~/.config/autostart
      file:
        path: "/home/{{ user }}/.config/autostart"
        state: directory
      become_user: "{{ user }}"
    - name: get new start script stats
      stat:
        path: "/home/{{ user }}/data/startup/start.desktop"
      register: new_start
    - name: setup start script
      block:
        # check start script is symlink and remove if not
        # otherwise SELinux prevents creating symlink from file
        - name: get old start script stats
          stat:
            path: "/home/{{ user }}/.config/autostart/start.desktop"
          register: old_start
        - name: remove old start script if not symlink
          file:
            state: absent
            path: "/home/{{ user }}/.config/autostart/start.desktop"
          when: >
            old_start.stat.exists == true and
            ( old_start.stat.islnk is not defined or old_start.stat.islnk == false )
        - name: symlink new start script
          file:
            src: "/home/{{ user }}/data/startup/start.desktop"
            dest: "/home/{{ user }}/.config/autostart/start.desktop"
            state: link
          become_user: "{{ user }}"
      when: new_start.stat.exists == true

    # install bat
    # otherwise cat does not work due to alias
    - name: install bat
      yum:
        name: bat
        state: present

    # install browsers
    - name: install chromium
      yum:
        name: chromium
        state: present
    - name: install firefox
      yum:
        name: firefox
        state: present

    # installing vlc
    # requires rmpfusion
    - name: get Fedora version
      shell: cut -d\  -f3 /etc/fedora-release
      register: fedora_version
    - name: install rpmfusion-free
      yum:
        name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm"
        state: present
    - name: install rpmfusion-nonfree
      yum:
        name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version.stdout }}.noarch.rpm"
        state: present
    - name: install vlc
      yum:
        name: vlc
        state: present

    # GNOME setup
    - name: install gnome-tweak-tool
      yum:
        name: gnome-tweak-tool
        state: present
    - name: install dconf-editor
      yum:
        name: dconf-editor
        state: present
    - name: setup GNOME config
      shell: /home/{{ user }}/data/config/gnome-config.sh

    # install development tools
    - name: install did
      yum:
        name: did
        state: present
    - name: create ~/.did
      file:
        path: "/home/{{ user }}/.did"
        state: directory
      become_user: "{{ user }}"
    - name: install httpie
      yum:
        name: httpie
        state: present
    - name: install jq
      yum:
        name: jq
        state: present
    - name: install meld
      yum:
        name: meld
        state: present

    # intall other random stuff
    - name: install feh
      yum:
        name: feh
        state: present
    - name: install kolourpaint
      yum:
        name: kolourpaint
        state: present
