# RH PS OSIDB setup playbook
#
#   full installation depends on ansible-prodsec.yml
#   ansible-osidb.yml
---
- name: osidb setup
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    - name: clone OSIDB git repo
      git:
        repo: "git@github.com:RedHatProductSecurity/osidb.git"
        dest: "/home/{{ user }}/prodsec/osidb"
        accept_hostkey: yes
        key_file: "/home/{{ user }}/.ssh/auto-install-key"
      become_user: "{{ user }}"

    - name: install deps
      dnf:
        name:
          - gcc
          - krb5-devel
          - libpq-devel
          - make
          - openldap-devel
          - podman
          - podman-compose
          - python3
          - python3-devel
          - tox
        state: present

    - name: setup env file
      file:
        src: "/home/{{ user }}/data/config/dot-env"
        dest: "/home/{{ user }}/prodsec/osidb/.env"
        state: link
      become_user: "{{ user }}"
