# RH PS Griffon setup playbook
#
#   full installation depends on ansible-prodsec.yml
#   ansible-griffon.yml
---
- name: griffon setup
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    - name: clone Griffon git repo
      git:
        repo: "git@github.com:RedHatProductSecurity/griffon.git"
        dest: "/home/{{ user }}/prodsec/griffon"
        accept_hostkey: yes
        key_file: "/home/{{ user }}/.ssh/auto-install-key"
      become_user: "{{ user }}"

    - name: install deps
      dnf:
        name:
          - gcc
          - krb5-libs
          - krb5-workstation
          - python3
          - python3-devel
          - virtualenv
        state: present

    - name: create venv
      shell: "python3 -m venv /home/{{ user }}/prodsec/griffon/venv"

    - name: install Griffon
      pip:
        name: griffon
        virtualenv: "/home/{{ user }}/prodsec/griffon/venv"

    - name: configure Griffon
      blockinfile:
        path: "/home/{{ user }}/prodsec/griffon/venv/bin/activate"
        marker: "# {mark} Griffon ANSIBLE MANAGED BLOCK"
        block: "{{ lookup('ansible.builtin.file', '/home/{{ user }}/data/config/griffon-venv') }}"

    - name: setup .bashrc
      blockinfile:
        path: "/home/{{ user }}/.bashrc"
        marker: "# {mark} Griffon ANSIBLE MANAGED BLOCK"
        block: |
          alias griffon-source="source ~/prodsec/griffon/venv/bin/activate"
