# RH PS work setup playbook
#
#   ansible-prodsec.yml
---
- name: prodsec setup
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    # TODO RHEL8 repo is no more
    # - name: create ~/prodsec
    #   file:
    #     path: "/home/{{ user }}/prodsec"
    #     state: directory
    #   become_user: "{{ user }}"

    # setup Kerberos
    - name: install krb5-workstation
      dnf:
        name: krb5-workstation
        state: present
    - name: setup Kerberos config
      copy:
        src: "/home/{{ user }}/data/config/krb5.conf"
        dest: "/etc/krb5.conf"
        mode: "0644"

    - name: add staging Jira redirection
      lineinfile:
        path: /etc/hosts
        line: "10.24.129.4 sso.stage.jboss.org"
        insertbefore: "127.0.0.1.*"
        state: present

    - name: install git
      dnf:
        name: git
        state: present

    - name: setup prodsec repositories
      block: []  # TODO rework

    - name: install development stuff
      dnf:
        name:
          - podman-compose
          - glibc-devel
          - libcap-devel
          - postgresql
          - postgresql-devel
          - krb5-devel
          - black
          - tox
          - gitk
          - sqlitebrowser
          - rpmdevtools
        state: present

    # TODO this got broken
    # - name: network proxy setup
    #   dconf:
    #     key: "{{ item.key }}"
    #     value: "{{ item.val }}"
    #     state: present
    #   become_user: "{{ user }}"
    #   loop:
    #     - key: "/org/gnome/system/proxy/mode"
    #       val: "auto"
    #     - key: "/org/gnome/system/proxy/autoconfig-url"
    #       val: "https://gitlab.corp.redhat.com/pac/proxy-pac/-/raw/main/proxy.pac"

    - name: install Slack
      community.general.snap:
        name: slack
        state: present

- name: osidb setup
  import_playbook: ansible-osidb.yml
