# RH PS work setup playbook
#
#   ansible-prodsec.yml
---
- name: prodsec setup
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    # TODO RHEL8 repo is no more
    # - name: create ~/prodsec
    #   file:
    #     path: "/home/{{ user }}/prodsec"
    #     state: directory
    #   become_user: "{{ user }}"

    # # setup VPN
    # - name: install NetworkManager-openvpn
    #   dnf:
    #     name: NetworkManager-openvpn
    #     state: present
    # - name: install NetworkManager-openvpn-gnome
    #   dnf:
    #     name: NetworkManager-openvpn-gnome
    #     state: present
    # - name: install redhat-internal-cert
    #   dnf:
    #     name: "https://hdn.corp.redhat.com/rhel8-csb/RPMS/noarch/redhat-internal-cert-install-0.1-25.el7.noarch.rpm"
    #     state: present
    # - name: import RHEL8 RPM GPG KEY
    #   rpm_key:
    #     key: "https://hdn.corp.redhat.com/rhel8-csb/RPM-GPG-KEY-helpdesk"
    #     state: present
    # - name: install redhat-internal-NetworkManager-openvpn-profiles
    #   dnf:
    #     name: redhat-internal-NetworkManager-openvpn-profiles
    #     enablerepo: "https://hdn.corp.redhat.com/rhel8-csb/rhel8-csb.repo"
    #     state: present

    # setup Kerberos
    - name: install krb5-workstation
      dnf:
        name: krb5-workstation
        state: present
    - name: setup Kerberos config
      copy:
        src: "/home/{{ user }}/data/config/krb5.conf"
        dest: "/etc/krb5.conf"
        mode: "0644"

    - name: add staging Jira redirection
      lineinfile:
        path: /etc/hosts
        line: "10.24.129.4 sso.stage.jboss.org"
        insertbefore: "127.0.0.1.*"
        state: present

    - name: install git
      dnf:
        name: git
        state: present

    - name: setup prodsec repositories
      block:
        # TODO key authentication does not work
        # - name: clone cee repo to dir
        #   git:
        #     repo: "git@gitlab.cee.redhat.com:{{ item.dir }}/{{ item.rep }}.git"
        #     dest: "/home/{{ user }}/prodsec/{{ item.rep }}"
        #     accept_hostkey: yes
        #     key_file: "/home/{{ user }}/.ssh/id_rsa"
        #   become_user: "{{ user }}"
        #   loop:
        #     - rep: "dashboard"
        #       dir: "prodsec-dev"
        #     - rep: "prodsec"
        #       dir: "prodsec-dev"
        #     - rep: "product-definitions"
        #       dir: "prodsec"
        #     - rep: "ps-constants"
        #       dir: "prodsec-dev"
        #     - rep: "sfm2"
        #       dir: "prodsec-dev"
        # - name: clone corp repo to dir
        #   git:
        #     repo: "git@gitlab.corp.redhat.com/product-security/dev/osidb-ops"
        #     dest: "/home/{{ user }}/prodsec/osidb-ops"
        #     accept_hostkey: yes
        #     key_file: "/home/{{ user }}/.ssh/id_rsa"
        #   become_user: "{{ user }}"
        - name: get new .sfm2clientrc stats
          stat:
            path: "/home/{{ user }}/data/config/dot-sfm2clientrc"
          register: new_sfm2clientrc
        - name: setup .sfm2clientrc
          file:
            src: "/home/{{ user }}/data/config/dot-sfm2clientrc"
            dest: "/home/{{ user }}/.sfm2clientrc"
            state: link
            force: true
          become_user: "{{ user }}"
          when: new_sfm2clientrc.stat.exists == true
      rescue:
        - name: report failure
          debug:
            msg: "prodsec repo failure - check VPN connection"

    - name: install stuff from prodsec repo
      block:
        - name: install prodsec repo
          dnf:
            name: https://prodsec.redhat.com/yum/prodsec-repo-latest.all.noarch.rpm
            state: present
            disable_gpg_check: true
      rescue:
        - name: report failure
          debug:
            msg: "prodsec repo failure - check VPN connection"
    - name: install development stuff
      dnf:
        name:
          - podman-compose
          - glibc-devel
          - libcap-devel
          - postgresql
          - postgresql-devel
          - krb5-devel
          - black
          - tox
          - gitk
          - sqlitebrowser
          - rpmdevtools
        state: present

    # TODO this got broken
    # - name: network proxy setup
    #   dconf:
    #     key: "{{ item.key }}"
    #     value: "{{ item.val }}"
    #     state: present
    #   become_user: "{{ user }}"
    #   loop:
    #     - key: "/org/gnome/system/proxy/mode"
    #       val: "auto"
    #     - key: "/org/gnome/system/proxy/autoconfig-url"
    #       val: "https://gitlab.corp.redhat.com/pac/proxy-pac/-/raw/main/proxy.pac"

    - name: install Slack
      dnf:
        name: https://downloads.slack-edge.com/releases/linux/4.35.121/prod/x64/slack-4.35.121-0.1.el8.x86_64.rpm
        state: present
        disable_gpg_check: true

- name: griffon setup
  import_playbook: ansible-griffon.yml

- name: osidb setup
  import_playbook: ansible-osidb.yml

- name: sfm2 setup
  import_playbook: ansible-sfm2.yml
