# hexchat setup playbook
#
#   ansible-hexchat.yml
---
- name: hexchat setup
  tags: hexchat
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    # HexChat
    - name: install hexchat
      dnf:
        name: hexchat
        state: present
    - name: create ~/.config/hexchat
      file:
        path: "/home/{{ user }}/.config/hexchat"
        state: directory
      become_user: "{{ user }}"
    - name: get new hexchat config stats
      stat:
        path: "/home/{{ user }}/data/config/servlist.conf"
      register: new_hexchat
    - name: setup hexchat config
      file:
        src: "/home/{{ user }}/data/config/servlist.conf"
        dest: "/home/{{ user }}/.config/hexchat/servlist.conf"
        state: link
        force: true
      become_user: "{{ user }}"
      when: new_hexchat.stat.exists == true
    - name: setup hexchat plugins
      git:
        repo: "git@github.com:osoukup/hexchat-plugins.git"
        dest: "/home/{{ user }}/.config/hexchat/addons/"
        accept_hostkey: yes
        key_file: "/home/{{ user }}/.ssh/auto-install-key"
      become_user: "{{ user }}"
