# RH PS OSIDB setup playbook
#
#   full installation depends on ansible-prodsec.yml
#   ansible-osidb.yml
---
- name: osidb setup
  hosts: all
  vars_prompt:
    # BZ API key to setup venv variable
    - name: bz_api_key
      prompt: "Production BZ API key"
    # Jira API token to setup venv variable
    - name: jira_aut_token
      prompt: "Production Jira API auth token"
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - bz_api_key is defined
          - user is defined

    # assume repository exists in ~/prodsec/osidb
    - name: get osidb dir stats
      stat:
        path: "/home/{{ user }}/prodsec/osidb"
      register: osidb_dir
    - name: setup osidb
      block:
        - name: install deps
          dnf:
            name:
              - gcc
              - krb5-devel
              - libpq-devel
              - make
              - openldap-devel
              - podman
              - podman-compose
              - python3
              - python3-devel
              - tox
            state: present

        - name: get env file stats
          stat:
            path: "/home/{{ user }}/prodsec/osidb/envvars"
          register: env_file
        - name: setup env file
          copy:
            dest: "/home/{{ user }}/prodsec/osidb/envvars"
            content: >
              export BZIMPORT_BZ_API_KEY={{ bz_api_key }}
              export JIRA_AUTH_TOKEN={{ jira_aut_token }}
              export OSI_DB_PASSWORD=passw0rd
              export ROOT_CA_PATH="/home/osoukup/prodsec/sfm2/sfm2/backends/ps_data_server/rest/it-root-ca.pem"
              export BZIMPORT_ENABLE_IMPORT_EMBARGOED=1
          become_user: "{{ user }}"
          when: env_file.stat.exists == false

      when: osidb_dir.stat.exists == true
    - name: report non-existing repo
      fail:
        msg: "osidb repo does not exist"
      when: osidb_dir.stat.exists == false
