# RH PS FlawDB setup playbook
#
#   full installation depends on ansible-prodsec.yml
#   ansible-flawdb.yml
---
- name: flawdb setup
  hosts: all
  vars_prompt:
    # BZ API key to setup venv variable
    - name: bz_api_key
      prompt: "Production BZ API key"
    # Jira API token to setup venv variable
    - name: jira_aut_token
      prompt: "Production Jira API auth token"
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - bz_api_key is defined
          - user is defined

    # assume repository exists in ~/prodsec/flawdb
    - name: get flawdb dir stats
      stat:
        path: "/home/{{ user }}/prodsec/flawdb"
      register: flawdb_dir
    - name: setup flawdb
      block:
        - name: install deps
          dnf:
            name:
              - gcc
              - krb5-devel
              - libpq-devel
              - make
              - openldap-devel
              - podman
              - podman-compose
              - python3
              - python3-devel
              - tox
            state: present

        - name: get env file stats
          stat:
            path: "/home/{{ user }}/prodsec/flawdb/envvars"
          register: env_file
        - name: setup env file
          copy:
            dest: "/home/{{ user }}/prodsec/flawdb/envvars"
            content: >
              export BZIMPORT_BZ_API_KEY={{ bz_api_key }}
              export JIRA_AUTH_TOKEN={{ jira_aut_token }}
              export FLAW_DB_PASSWORD=passw0rd
          become_user: "{{ user }}"
          when: env_file.stat.exists == false

      when: flawdb_dir.stat.exists == true
    - name: report non-existing repo
      fail:
        msg: "flawdb repo does not exist"
      when: flawdb_dir.stat.exists == false
