" vim config
" comment
"
" no vi compatibility even whet config used another than .vimrc way
set nocompatible

" improve highlight
highlight Search cterm=NONE ctermfg=darkgreen ctermbg=yellow
highlight Flake8_Error cterm=NONE ctermfg=white ctermbg=red
highlight Flake8_Warning cterm=NONE ctermfg=white ctermbg=yellow
highlight Flake8_PyFlake cterm=NONE ctermfg=white ctermbg=blue
highlight Flake8_Complexity cterm=NONE ctermfg=white ctermbg=blue
highlight Flake8_Naming cterm=NONE ctermfg=white ctermbg=blue
highlight DiffAdd cterm=NONE ctermfg=NONE ctermbg=darkgrey
highlight DiffText cterm=NONE ctermfg=NONE ctermbg=darkgrey
" syntax highlight
syntax on
" file type detection and type plugin and indention file loading
filetype indent plugin on

" line numbers on
set number

" line wrapping off
" do not cut long lines
set nowrap

" scroll offset
" cursor verticaly centered
set scrolloff=999

" replace tab with spaces
set tabstop=4 shiftwidth=4 expandtab

" keyboard remapping
" shift arrows
noremap ů l
noremap l k
noremap k j
noremap j h
noremap h ů
" shift window movement
noremap <c-w>ů <c-w>l
noremap <c-w>l <c-w>k
noremap <c-w>k <c-w>j
noremap <c-w>j <c-w>h
noremap <c-w>h <c-w>ů

" remap leader key from \
let mapleader="h"

" system clipboard yank
vnoremap <leader>y "+y

" STATUS LINE
"
" show status line also for single buffer opened
set laststatus=2

set statusline=
set statusline+=%#CursorLine#
set statusline+=%{FugitiveStatusline()}
set statusline+=%#StatusLine#
set statusline+=\ %f
set statusline+=%=
set statusline+=\ %y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\[%{&fileformat}\]
set statusline+=\ %p%%
set statusline+=\ %l:%c
set statusline+=\ 

" PLUGINS
"
" pathogen : plugin manager
execute pathogen#infect()

" NERDTree
autocmd vimenter * NERDTree
autocmd vimenter * wincmd l
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" vim-autoflake
let g:autoflake_remove_all_unused_imports=1
let g:autoflake_remove_unused_variables=1

" vim-flake8
autocmd FileType python map <buffer> <leader>f :call flake8#Flake8()<CR>

" vim-ctrlp
let g:ctrlp_custom_ignore = 'flask\|node_modules\|venv'

" PLUGINS OPTIONS REWRITE
" this must be after plugins load to rewrite their options
"
" search for word under cursor
" <cword> stands for current word
" <bar> stands for vertical bar separator
noremap <leader>s :execute "vimgrep /" . expand("<cword>") . "/j **" <bar> cw<CR>
" however ignore useless directories
:set wildignore+=flask/**,**node_modules/**,venv/**
