# Tiddly Wiki setup playbook
#
#   ansible-wiki.yml
---
- name: wiki setup
  hosts: all
  become: true
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    - name: install nodejs
      dnf:
        name: nodejs
        state: present

    # wiki synced from Dropbox required to work

    - name: setup wiki unit file
      template:
        src: "/home/{{ user }}/osoukup/setup/wiki/wiki.service.template"
        dest: "/lib/systemd/system/wiki.service"

    - name: enable and start wiki service
      systemd:
        name: wiki.service
        state: started
        enabled: yes

    - name: ensure log directory exists
      file:
        path: "/home/{{ user }}/log/TiddlyWiki"
        owner: "{{ user }}"
        group: "{{ user }}"
        state: directory
        mode: 0644
        access_time: preserve
        modification_time: preserve

    - name: ensure error log file exists
      file:
        path: "/home/{{ user }}/log/TiddlyWiki/node.err"
        owner: "{{ user }}"
        group: "{{ user }}"
        state: touch
        mode: 0644
        access_time: preserve
        modification_time: preserve

    - name: ensure output log file exists
      file:
        path: "/home/{{ user }}/log/TiddlyWiki/node.out"
        owner: "{{ user }}"
        group: "{{ user }}"
        state: touch
        mode: 0644
        access_time: preserve
        modification_time: preserve
