# Tiddly Wiki setup playbook
#
#   ansible-wiki.yml
---
- name: wiki setup
  hosts: all
  become: true
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined

    - name: install nodejs
      dnf:
        name: nodejs
        state: present

    # wiki synced from Dropbox required to work

    - name: setup wiki unit file
      template:
        src: "/home/{{ user }}/osoukup/setup/wiki/wiki.service.template"
        dest: "/lib/systemd/system/wiki.service"

    - name: enable and start wiki service
      systemd:
        name: wiki.service
        state: started
        enabled: yes
